package io.xymul.xmpp.xmake2cmake.settings

import com.intellij.openapi.options.ConfigurationException
import com.intellij.openapi.options.SearchableConfigurable
import com.intellij.ui.components.JBTextField
import java.awt.GridBagConstraints
import java.awt.GridBagLayout
import java.awt.Insets
import java.io.File
import javax.swing.ButtonGroup
import javax.swing.JComponent
import javax.swing.JLabel
import javax.swing.JPanel
import javax.swing.JRadioButton

/**
 * Settings page registered below `Settings | Tools | Automatic XMake2CMake`.
 */
class XMake2CMakeConfigurable : SearchableConfigurable {

    private val confirmRadioButton = JRadioButton("Ask for confirmation before every automatic generation")
    private val autoRadioButton = JRadioButton("Generate automatically, without asking")
    private val disabledRadioButton = JRadioButton("Disable automatic generation")

    private val xmakePathField = JBTextField()
    private val extraArgumentsField = JBTextField()
    private val timeoutField = JBTextField()

    private var rootPanel: JPanel? = null

    override fun getId(): String = "io.xymul.xmpp.xmake2cmake.settings"

    override fun getDisplayName(): String = "Automatic XMake2CMake"

    override fun createComponent(): JComponent {
        rootPanel?.let { return it }

        ButtonGroup().apply {
            add(confirmRadioButton)
            add(autoRadioButton)
            add(disabledRadioButton)
        }

        val panel = JPanel(GridBagLayout())
        var row = 0

        panel.add(
            JLabel("<html><b>When an xmake.lua was changed (Ctrl+S, or its editor tab was closed)</b></html>"),
            gridBag(0, row++, width = 2, weightX = 1.0)
        )
        panel.add(confirmRadioButton, gridBag(0, row++, width = 2, weightX = 1.0))
        panel.add(autoRadioButton, gridBag(0, row++, width = 2, weightX = 1.0))
        panel.add(disabledRadioButton, gridBag(0, row++, width = 2, weightX = 1.0))
        panel.add(
            JLabel(
                "<html><body style='width:420px'>Before generating, the project description is validated by " +
                        "running <code>xmake f -y</code>. <code>CMakeLists.txt</code> is only (re)generated by " +
                        "<code>xmake project -k cmake -y</code> when that validation succeeded. Both commands run " +
                        "in the directory of the changed <code>xmake.lua</code>.</body></html>"
            ),
            gridBag(0, row++, width = 2, weightX = 1.0, top = 12)
        )

        panel.add(
            JLabel("<html><b>xmake executable</b></html>"),
            gridBag(0, row++, width = 2, weightX = 1.0, top = 12)
        )
        panel.add(JLabel("Path (optional):"), gridBag(0, row))
        panel.add(xmakePathField, gridBag(1, row++, weightX = 1.0))
        panel.add(
            JLabel(
                "<html><body style='width:420px'>Leave empty to use the toolkit configured in the XMake plugin, " +
                        "or the <code>xmake</code> found on the <code>PATH</code>.</body></html>"
            ),
            gridBag(1, row++, weightX = 1.0)
        )
        panel.add(JLabel("Extra arguments:"), gridBag(0, row))
        panel.add(extraArgumentsField, gridBag(1, row++, weightX = 1.0))
        panel.add(
            JLabel(
                "<html><body style='width:420px'>Appended to both commands, e.g. " +
                        "<code>-p windows -a x64 -m debug</code>.</body></html>"
            ),
            gridBag(1, row++, weightX = 1.0)
        )
        panel.add(JLabel("Timeout (seconds):"), gridBag(0, row))
        panel.add(timeoutField, gridBag(1, row++, weightX = 1.0))

        // Push everything to the top.
        panel.add(JPanel(), gridBag(0, row, width = 2, weightX = 1.0, weightY = 1.0))

        rootPanel = panel
        return panel
    }

    override fun isModified(): Boolean {
        val state = XMake2CMakeSettings.getInstance().normalized()
        return selectedPolicy() != state.generationPolicy ||
                unquote(xmakePathField.text.trim()) != state.xmakeExecutablePath ||
                extraArgumentsField.text.trim() != state.extraXmakeArguments ||
                timeoutField.text.trim() != state.timeoutSeconds.toString()
    }

    override fun apply() {
        val state = XMake2CMakeSettings.getInstance().normalized()

        val xmakePath = unquote(xmakePathField.text.trim())
        if (xmakePath.isNotEmpty() && !File(xmakePath).isFile) {
            throw ConfigurationException("The xmake executable does not exist: $xmakePath")
        }

        val timeout = timeoutField.text.trim().toIntOrNull()
        if (timeout == null || timeout <= 0) {
            throw ConfigurationException("The timeout has to be a positive number of seconds.")
        }

        state.generationPolicy = selectedPolicy()
        state.xmakeExecutablePath = xmakePath
        state.extraXmakeArguments = extraArgumentsField.text.trim()
        state.timeoutSeconds = timeout
    }

    override fun reset() {
        val state = XMake2CMakeSettings.getInstance().normalized()
        when (state.generationPolicy) {
            GenerationPolicy.AUTO -> autoRadioButton.isSelected = true
            GenerationPolicy.DISABLED -> disabledRadioButton.isSelected = true
            else -> confirmRadioButton.isSelected = true
        }
        xmakePathField.text = state.xmakeExecutablePath
        extraArgumentsField.text = state.extraXmakeArguments
        timeoutField.text = state.timeoutSeconds.toString()
    }

    override fun disposeUIResources() {
        rootPanel = null
    }

    private fun selectedPolicy(): GenerationPolicy = when {
        autoRadioButton.isSelected -> GenerationPolicy.AUTO
        disabledRadioButton.isSelected -> GenerationPolicy.DISABLED
        else -> GenerationPolicy.CONFIRM
    }

    private fun unquote(value: String): String =
        if (value.length >= 2 && value.first() == value.last() && (value.first() == '"' || value.first() == '\'')) {
            value.substring(1, value.length - 1)
        } else {
            value
        }

    private fun gridBag(
        x: Int,
        y: Int,
        width: Int = 1,
        weightX: Double = 0.0,
        weightY: Double = 0.0,
        top: Int = 0
    ): GridBagConstraints = GridBagConstraints().apply {
        gridx = x
        gridy = y
        gridwidth = width
        this.weightx = weightX
        this.weighty = weightY
        anchor = GridBagConstraints.WEST
        fill = if (weightX > 0.0) GridBagConstraints.HORIZONTAL else GridBagConstraints.NONE
        insets = Insets(top, 4, 2, 4)
    }
}
